lmctl/drivers/lm/resource_pkg.py
=> Resolves #16 by ensuring auth headers are added to Resource onboarding requests

lmctl/cli/ctlmgmt.py
Fixes #13 by ensuring the errors thrown when retrieving the config co…
=> Fixes #13 by capturing config load errors

docs/command-reference/pkg/inspect.md, lmctl/cli/commands/pkg.py, lmctl/cli/format.py, lmctl/project/package/core.py, lmctl/project/package/meta.py, tests/unit/cli/commands/test_deployment_location.py, tests/unit/cli/commands/test_lifecycledriver.py, tests/unit/cli/commands/test_vimdriver.py, tests/unit/project/package/test_core.py
=> Add pkg inspect command to view contents of a package

docs/index.md, lmctl/cli/ctlmgmt.py
Closes #22 by removing the undefined variable and setting the correct value on the password prompt "hidden" property.
=> Remove undefined variable "secret". Set hidden value to True

lmctl/project/package/core.py, lmctl/project/processes/package.py, lmctl/project/source/core.py
=> Ensure package is built in directory relative to the project

docs/configure.md, example-config.yaml, lmctl/ctl/environments.py, lmctl/drivers/lm/base.py, lmctl/drivers/lm/security.py, lmctl/environment/lmenv.py, tests/unit/environment/test_lmenv.py
=> Support subpath access to API and support /ui subpath for UI access

MANIFEST.in, docs/command-reference/project/create.md, docs/projects/creating-projects.md, lmctl/cli/commands/project.py, lmctl/project/handlers/assembly/assembly_src.py, lmctl/project/handlers/brent/brent_src.py, lmctl/project/handlers/brent/sol003/scripts/CreateVnfRequest.js, lmctl/project/handlers/brent/sol003/scripts/HealVnfRequest.js, lmctl/project/handlers/brent/sol003/scripts/InstantiateVnfRequest.js, lmctl/project/handlers/brent/sol003/scripts/OperateVnfRequest-Start.js, lmctl/project/handlers/brent/sol003/scripts/OperateVnfRequest-Stop.js, lmctl/project/handlers/brent/sol003/scripts/ScaleVnfRequest.js, lmctl/project/handlers/brent/sol003/scripts/TerminateVnfRequest.js, lmctl/project/handlers/brent/sol003/scripts/VnfInstance.js, lmctl/project/handlers/interface.py, lmctl/project/handlers/resource/resource_src.py, lmctl/project/source/creator.py, lmctl/utils/descriptors.py, tests/common/project_testing.py, tests/integration/project/brenttests/test_create.py
Support lifecycle and inf params on Brent source creation. 
Closes #30
=> Support configurable params on create Project request

lmctl/cli/commands/project.py, lmctl/project/package/core.py, lmctl/project/processes/testing.py, tests/integration/project/assemblytests/test_test.py
Fix for #69. 
Changes submitted by Jim Hardwicke (IBM) but he was unable to gain access so this was deemed the quickest way.
=> issue/69 - pass test names through from cmd

lmctl/cli/arguments/file_input.py, lmctl/cli/commands/lifecycledriver.py, lmctl/cli/commands/targets/assemblies.py, lmctl/cli/commands/vimdriver.py, lmctl/client/client.py, lmctl/utils/trace_ctx.py, tests/unit/client/test_client.py, tests/unit/utils/test_trace_ctx.py
Include context in headers.
Extra command doc fixes.
Closes #78
=> issue/78 - support tracing context.

docs/configure.md, lmctl/cli/commands/pkg.py, lmctl/cli/commands/project.py, lmctl/cli/lifecycle.py, lmctl/drivers/lm/__init__.py, lmctl/drivers/lm/etsipkgmgmtdriver.py, lmctl/drivers/lm/packagemgmtdriver.py, lmctl/environment/lmenv.py, lmctl/project/handlers/assembly/__init__.py, lmctl/project/handlers/brent/__init__.py, lmctl/project/handlers/brent/brent_content.py, lmctl/project/handlers/etsi_ns/__init__.py, lmctl/project/handlers/etsi_ns/etsi_ns_content.py, lmctl/project/handlers/etsi_ns/etsi_ns_src.py, lmctl/project/handlers/etsi_vnf/__init__.py, lmctl/project/handlers/etsi_vnf/etsi_vnf_content.py, lmctl/project/handlers/etsi_vnf/etsi_vnf_src.py, lmctl/project/handlers/interface.py, lmctl/project/handlers/manager.py, lmctl/project/package/core.py, lmctl/project/package/meta.py, lmctl/project/processes/etsi_push.py, lmctl/project/processes/staging.py, lmctl/project/source/config.py, lmctl/project/source/creator.py, lmctl/project/types.py
Add ETSI_NS (based on Assembly) and ETSI_VNF (based on Resource) project types.
Logic to create, build (package) and push to TNC-O. push logic uses the SOL005 VNF and NSD API's from TNC-O 2.1.1
=> Feature/tnc o tracking/498

docs/command-reference/project/create.md, docs/projects/creating-projects.md, docs/projects/overview.md
Documentation additions for the recent ETSI work.
=> Etsi project documentation

lmctl/project/source/creator.py
=> issue/118 - print name of project in statement

lmctl/cli/commands/login.py, lmctl/environment/__init__.py, lmctl/environment/lmenv.py, tests/unit/cli/commands/test_config.py, tests/unit/cli/commands/test_login.py, tests/unit/config/config_files/alm-and-tnco-key.yaml, tests/unit/config/config_files/alm-key.yaml, tests/unit/config/config_files/lm-and-alm-key.yaml, tests/unit/config/config_files/lm-and-tnco-key.yaml, tests/unit/config/config_files/lm-key.yaml, tests/unit/config/config_files/simple-config.yaml, tests/unit/config/config_files/tnco-in-parts.yaml, tests/unit/config/config_files/tnco-key.yaml, tests/unit/config/test_io.py, tests/unit/config/test_parser.py, tests/unit/environment/test_lmenv.py
=> Issue/153 - use "https" as the default for address discourage the use of "http"

docs/command-reference/login.md, docs/configure.md, docs/getting-started.md, lmctl/cli/commands/login.py, lmctl/client/__init__.py, lmctl/client/api/auth.py, lmctl/client/client_builder.py, lmctl/client/client_credentials_auth.py, lmctl/client/constants.py, lmctl/client/okta_client_credentials_auth.py, lmctl/client/pass_auth.py, lmctl/drivers/lm/security.py, lmctl/environment/lmenv.py, tests/integration/cli/test_login.py, tests/integration/integration_test_properties.py, tests/unit/environment/test_lmenv.py
[Okta_settings.docx](https://github.com/IBM/lmctl/files/9888092/Okta_settings.docx)
=> Add support for Okta oauth2 integration

lmctl/files.py, lmctl/project/package/core.py, tests/common/project_testing.py, tests/unit/test_files.py
Consuming the change from #152 to fix CVE-2007-4559. Adjusted to move changes to a utility method and to add unit tests
=> Vulnerability fix for CVE-2007-4559

docs/command-reference/login.md, docs/configure.md, docs/getting-started.md
Okta integration only works with resource owner password flow which is not recommended.
=> issue/169 Reduce Okta docs to cli reference only.

docs/command-reference/index.md, docs/command-reference/whoami.md, lmctl/cli/commands/__init__.py, lmctl/cli/commands/env.py, lmctl/cli/commands/whoami.py, lmctl/cli/controller.py, lmctl/cli/entry.py, lmctl/client/auth_tracker.py, lmctl/environment/lmenv.py, lmctl/utils/jwt.py, tests/integration/cli/test_env.py, tests/unit/cli/commands/test_login.py, tests/unit/cli/commands/test_processes.py, tests/unit/cli/commands/test_whoami.py, tests/unit/client/token_helper.py
=> Issue/154 - whoami command

lmctl/cli/commands/resource_managers.py
=> issue/151 Hide RM commands

.travis.yml
Switching to a newer OS version. This includes the updated ssl module.
=> Build fixes for Openssl issue

.travis.yml, CONTRIBUTING.md, DESCRIPTION.md, Readme.md, developer_docs/release.md
Will merge once branch is renamed
=> Rename master branches to main in public repos

lmctl/cli/arguments/environment_name.py, lmctl/cli/commands/object_groups.py, lmctl/client/api/object_groups.py, tests/unit/cli/commands/test_object_groups.py, tests/unit/client/api/test_object_groups.py
=> Support for retrieving the default object group
